name: CI
permissions:
  contents: read

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install modules
      run: npm ci
    - name: Install Playwright browser
      run: npx playwright install --with-deps chromium
    - name: Run ESLint
      run: npm run lint
    - name: Run automated tests
      run: npm run test:ci
