name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - run: |
          mkdir public
          cp src/js/data-layer/com_wiki.json public/com_wiki.json
          cp www/data/mixte.json public/mixte.json
          cp www/data/plan-ign-interactif-style.json public/plan-ign-interactif-style.json
          cp www/data/poi-osm-style.json public/poi-osm-style.json
          sed -i 's/\"sprite\": \"data/\"sprite\": \"https:\/\/ignf.github.io\/cartes-ign-app\/data/g' public/mixte.json
          sed -i 's/\"sprite\": \"data/\"sprite\": \"https:\/\/ignf.github.io\/cartes-ign-app\/data/g' public/plan-ign-interactif-style.json
          sed -i 's/\"sprite\": \"data/\"sprite\": \"https:\/\/ignf.github.io\/cartes-ign-app\/data/g' public/poi-osm-style.json
          mkdir public/data
          cp www/data/poi-osm-sprite.png public/data/poi-osm-sprite.png
          cp www/data/poi-osm-sprite.json public/data/poi-osm-sprite.json
          cp www/data/poi-osm-sprite@2x.png public/data/poi-osm-sprite@2x.png
          cp www/data/poi-osm-sprite@2x.json public/data/poi-osm-sprite@2x.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
