name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - run: |
          cp src/js/data-layer/com_wiki.json docs/com_wiki.json
          cp www/data/mixte.json docs/mixte.json
          cp www/data/plan-ign-interactif-style.json docs/plan-ign-interactif-style.json
          cp www/data/poi-osm-style.json docs/poi-osm-style.json
          mkdir docs/data
          cp www/data/poi-osm-sprite.png docs/data/poi-osm-sprite.png
          cp www/data/poi-osm-sprite.json docs/data/poi-osm-sprite.json
          cp www/data/poi-osm-sprite@2x.png docs/data/poi-osm-sprite@2x.png
          cp www/data/poi-osm-sprite@2x.json docs/data/poi-osm-sprite@2x.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
